modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="glore" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Glowing Ores" #mandatory
logoFile="examplemod.png" #optional
credits="Apothic0n" #optional
authors="Apothic0n" #optional
description='''
Glowing Ores:

Making the ores glow!
'''